# Setup dockerized app for testing purposes on local machine
version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: myforumwebapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  server:
    build:
      context: ./server
    image: panda1920/forumapp-server:latest
    container_name: myforumwebapp-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    # docker specific env overrides the default .env
    environment:
      - MONGO_HOSTNAME=myforumwebapp-mongo
      - MONGO_PORT=27017

  client:
    build:
      context: ./client
    image: panda1920/forumapp-client:latest
    container_name: myforumwebapp-client
    ports:
      - '8080:80'

volumes:
  mongo_data:
  mongo_config:
