version: 2.1
jobs:
  test_server:
    # working_directory: ~/project/server
    # the default working directory is ~/project
    docker:
      - image: circleci/python:3.7.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          name: Restoring dependency cache if possible
          keys:
            - deps-v1-{{ checksum "./server/Pipfile.lock"}}
            - deps-v1-
      - run:
          name: Install dependencies
          command: |
            cd ./server
            sudo pip install pipenv
            pipenv install -d
      - save_cache:
          name: Saving dependency cache if needed
          key: deps-v1-{{ checksum "./server/Pipfile.lock"}}
          paths:
            - "/server/.venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.7/site-packages"
      - run:
          name: Run tests
          command: |
            cd ./server
            pipenv run testl
  
  # test_client:
  #   docker:
  #     - image: circleci/node:12.2
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           cd ./client
  #           sudo npm install
  #     - run:
  #         name: Run tests
  #         command: |
  #           cd ./client
  #           npm run test

workflows:
  version: 2.1
  test_codebase:
    jobs:
      - test_server
      # - test_client
