version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo "hello World"
      - run:
          name: random commands
          command: |
            echo $PWD
            ls -al
      - run:
          name: Check environment variables exist
          command: |
            echo $SECRET_KEY
            echo $DATA_LOCATION
      # - run:
      #     name: Install dependencies
      #     command: |
      #       pip install pipenv
      #       pipenv install -d
      #       pipenv shell
