version: 2.1
jobs:
  build:
    working_directory: ~/project/server
    docker:
      - image: circleci/python:3.7.0
        environment:
            PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo "hello World"
      - run:
          name: Check environment variables exist
          command: |
            echo $SECRET_KEY
            echo $DATA_LOCATION
            echo $PIPENV_VENV_IN_PROJECT
      - run:
          name: Install dependencies
          command: |
            cd ./server
            pip install pipenv
            pipenv install -d
      - run:
          name: Run tests
          command: |
            echo $PWD
            cd ./server
            ls -al
