version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo "hello World"
      - run:
          name: random commands
          command: |
            echo $PWD
            ls -al