version: 2.1
jobs:
  test_server:
    # working_directory: ~/project/server
    # the default working directory is ~/project
    docker:
      - image: circleci/python:3.7.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
          MONGO_HOSTNAME: localhost
          MONGO_PORT: 27017
      
      # docker image for test db
      - image: circleci/mongo:4.2

    steps:
      - checkout
      - run:
          name: Changing file permissiosn for later steps
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          name: Restoring dependency cache if possible
          keys:
            - deps-v2-{{ checksum "./server/Pipfile.lock"}}
            - deps-v2-
      - run:
          name: Install dependencies
          command: |
            cd ./server
            sudo pip install pipenv
            pipenv install -d
      - run:
          name: Run tests
          command: |
            cd ./server
            pipenv run test
      - save_cache:
          name: Saving dependency cache
          key: deps-v2-{{ checksum "./server/Pipfile.lock"}}
          paths:
            - "./server/.venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.7/site-packages"
  
  test_client:
    docker:
      - image: circleci/node:12.2
    steps:
      - checkout
      - restore_cache:
          name: Restoring dependency cache if possible
          keys:
            - deps-client-v1-{{ checksum "./client/package-lock.json"}}
            - deps-client-v1-
      - run:
          name: Install dependencies
          command: |
            cd ./client
            npm install
      - run:
          name: Run tests
          command: |
            cd ./client
            npm run test
      - save_cache:
          name: Saving dependency cache
          key: deps-client-v1-{{ checksum "./client/package-lock.json"}}
          paths:
            - "./node_modules"

  publish_server:
    docker:
      - image: circleci/python:3.7.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            cd ./server
            pwd
            sudo pip install pipenv
      - run:
          name: Dockerize the app and create image
          command: |
            cd ./server
            pwd
            pipenv run dockerize
      - run:
          name: Push created image to dockerhub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

workflows:
  version: 2.1
  test_codebase:
    jobs:
      - test_server
      - test_client
      - publish_server:
        requires:
          - test_server
