from passlib.context import CryptContext

class UserAuthentication:
    """
    A namespace to put all user authentication related stuff
    such as passwords.
    """

    # context file used to hash/verify passwords
    _context = CryptContext(
        schemes=['pbkdf2_sha256'],
        deprecated='auto'
    )

    @classmethod
    def hashPassword(cls, password):
        return cls._context.hash(password)

    @classmethod
    def verifyPassword(cls, password, hash):
        try:
            return cls._context.verify(password, hash)
        except:
            # hash generated by different context raises exception
            return False