# -*- coding: utf-8 -*-
"""
This file houses class that serves the app with auth related methods
"""

import logging

from passlib.context import CryptContext

import server.exceptions as exceptions


class UserAuthentication:
    """
    A namespace to put all user authentication related services
    such as passwords hashing.
    """

    # context file used to hash/verify passwords
    _context = CryptContext(
        schemes=['pbkdf2_sha256'],
        deprecated='auto'
    )

    @classmethod
    def hashPassword(cls, password):
        """
        Hashes password to be stored in database
        
        Args:
            password(str): password to hash
        Returns:
            str: hashed password
        """
        return cls._context.hash(password)

    @classmethod
    def verifyPassword(cls, password, hash):
        """
        verify password so that it matches hash
        
        Args:
            password(str): plain text password to verify
            hash(str): hashed password that plain password is matched against
        Returns:
            boolean: whether verification succeeded or not
        """
        try:
            return cls._context.verify(password, hash)
        except Exception:
            # hash generated by different context raises exception
            return False

    def __init__(self, repo, filter_class, session_manager):
        self._repo = repo
        self._filter = filter_class
        self._session = session_manager

    def login(self, userName, password):
        """
        provides login service
        checks credentials against user in repo,
        and if matches put userinformation in session
        
        Args:
            userName(str): plain text username
            password(str): plain text password
        Returns:
            None
        """
        if not userName or not password:
            logging.info('Invalid user credentials')
            raise exceptions.InvalidUserCredentials('Invalid credentials')

        user = self._searchUserFromRepo(userName)
        if not self.verifyPassword(password, user['password']):
            logging.info('Failed to verify password')
            raise exceptions.InvalidUserCredentials('Incorrect password')

        self._session.setSessionUser(user)

    def _searchUserFromRepo(self, userName):
        searchFilter = self._filter.createFilter(dict(
            field='userName', operator='eq', value=[userName]
        ))
        
        result = self._repo.searchUser(searchFilter)
        try:
            return result['users'][0]
        except Exception as e:
            logging.error(e)
            raise exceptions.InvalidUserCredentials('Email not registered')
