# -*- coding: utf-8 -*-
"""
This file houses class that serves the app with auth related methods
"""

import logging

from passlib.context import CryptContext

from server.database.filter import PrimitiveFilter
import server.exceptions as exceptions

logger = logging.getLogger(__name__)


class PasswordService:
    """
    namepace to put all password related methods
    """
    # context file used to hash/verify passwords
    _context = CryptContext(
        schemes=['pbkdf2_sha256'],
        deprecated='auto'
    )

    @classmethod
    def hashPassword(cls, password):
        """
        Hashes password to be stored in database
        
        Args:
            password(str): password to hash
        Returns:
            str: hashed password
        """
        logger.info('Hashing password')
        return cls._context.hash(password)

    @classmethod
    def verifyPassword(cls, password, hash):
        """
        verify password so that it matches hash
        
        Args:
            password(str): plain text password to verify
            hash(str): hashed password that plain password is matched against
        Returns:
            bool: whether verification succeeded or not
        """
        logger.info('Verifying password')
        try:
            return cls._context.verify(password, hash)
        except Exception:
            # hash generated by different context raises exception
            return False


class UserAuthenticationService:
    """
    Class that provides login/logout functionality to the app.
    Houses business logic related to such authentication process.
    """
    def __init__(self, repo, session_manager):
        self._repo = repo
        self._session = session_manager

    def login(self, credential):
        """
        provides login service
        checks credential against user in repo,
        and if matches put userinformation in session
        
        Args:
            credential(dict): dictionary that contains user credential
        Returns:
            None
        """
        logger.info('Authenticating credentials')
        userName, password = self._extractUserNameAndPassword(credential)
        user_indb = self._searchUserFromRepo(userName)

        if not PasswordService.verifyPassword(password, user_indb.password):
            logger.info('Failed to verify password')
            raise exceptions.InvalidUserCredentials('Incorrect password')

        self._session.set_user(user_indb)

    def _extractUserNameAndPassword(self, credential):
        userName = credential.get('userName', None)
        password = credential.get('password', None)

        if not userName or not password:
            logger.info('Invalid user credential')
            raise exceptions.InvalidUserCredentials('Invalid credential')

        return (userName, password)

    def _searchUserFromRepo(self, userName):
        searchFilter = PrimitiveFilter.createFilter(dict(
            field='userName', operator='eq', value=[userName]
        ))
        
        result = self._repo.searchUser(searchFilter)
        try:
            return result['users'][0]
        except Exception as e:
            logger.error(e)
            raise exceptions.InvalidUserCredentials('Email not registered')

    def logout(self):
        """
        provides logout service
        
        Args:
            None
        Returns:
            None
        """
        logger.info('Logout user')
        self._session.remove_user()

    def confirm_session_credentials(self, password):
        """
        confirms that password is correct for current session user.
        
        Args:
            password(str): plain text password for the current session user
        Returns:
            bool: True if correct
        Raises:
            InvalidUserCredentials: if password is incorrect
        """
        logger.info('Verifying session user credentials')
        session_user = self._session.get_user()

        if not PasswordService.verifyPassword(password, session_user.password):
            logger.info('Invalid user credential')
            raise exceptions.InvalidUserCredentials('Invalid credentials')

        return True
